# [START runtime]
runtime: python27
service: ui
threadsafe: yes
# [END runtime]
env_variables:
  NODE_ENV: production
  BASE_API_URL: https://back-dot-pe-pacasmayo-siscred-gcp-dev.uc.r.appspot.com
  clientId: 311178255527-hh0kq3ccrf68j5kusbeprulhmou3v3mt.apps.googleusercontent.com
  CLIENT_ID: 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
  CLIENT_KEY: 311178255527-hh0kq3ccrf68j5kusbeprulhmou3v3mt.apps.googleusercontent.com
handlers:
- url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
  static_files: dist/\1
  upload: dist/(.*)(|\.map)
  secure: always
- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
skip_files:
- ^(?!dist)  # Skip any files not in the dist folder