
export const GlobalSettings = Object.freeze({

    //BASE_API_URL: 'http://localhost:8080',
    //BASE_API_URL: 'https://back-dot-pe-pacasmayo-siscred-gcp-dev.uc.r.appspot.com',
    N_COLUMNAS_GRID: 4,

    /*     clientId: "3723124560-9b6f7hotqq80p7cean40228i8ea7j335.apps.googleusercontent.com",
        CLIENT_ID: 'PFryqr66AXV7uv0bNnsvx3KW',
        CLIENT_KEY: '3723124560-9b6f7hotqq80p7cean40228i8ea7j335.apps.googleusercontent.com',
     */
    //clientId: "311178255527-hh0kq3ccrf68j5kusbeprulhmou3v3mt.apps.googleusercontent.com",
    //CLIENT_ID:'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',
    //CLIENT_KEY: '311178255527-hh0kq3ccrf68j5kusbeprulhmou3v3mt.apps.googleusercontent.com',

    //Perfiles
    PERFIL_ADMINISTRADOR: 2,
    PERFIL_USUARIO: 1,

    //Roles
    ROL_SOLICITANTE: 10,
    ROL_REVISOR: 20,
    ROL_CONTROL_GESTION: 21,
    ROL_RPA: 30,
    ROL_EVALUADOR: 40,
    ROL_APROBADOR:60,
    ROL_SUPLENTE: 50,

    ROL_COSTOS: 4,
    ROL_COMERCIAL: 5,
    ROL_ADMINISTRADOR_MATERIAL: 6,
    ROL_SAP: 7,
    ROL_MARKETING: 10,

    //Estados
    ESTADO_SOLICITUD_EN_SOLICITANTE: 10,
    ESTADO_SOLICITUD_EN_REVISION: 20,
    ESTADO_SOLICITUD_EN_RPA: 30,
    ESTADO_SOLICITUD_EN_EVALUACION: 40,
    ESTADO_SOLICITUD_EN_APROBACION: 50,

    ESTADO_SOLICITUD_ANULADO: 2,
    ESTADO_SOLICITUD_EN_ADMINISTRACION: 7,
    ESTADO_SOLICITUD_EN_CONTROL_GESTION: 10,
    ESTADO_SOLICITUD_EN_SAP: 8,
    ESTADO_SOLICITUD_FINALIZADO: 9,
    ESTADO_SOLICITUD_EN_MARKETING: 11,
    ESTADO_SOLICITUD_EN_APROBACION_FINAL: 12,
    ESTADO_SOLICITUD_FINALIZADO_FACTURACION: 13,


    //para consulta de solicutdes
    SOLICITUD_DETALLE_NUMERO_COLUMNAS: 6,
    PAGINA_INICIO: 1,
    CANTIDAD_FILAS: 15,
    CANTIDAD_FILAS_MATERIALES: 100,

    //Tipo d Linea de credito
    LINEA_REGULAR: 1,
    LINEA_TEMPORAL: 2,

    //Vigencias - LINEA TEMPORAL
    PICO_DEMANDA: 1,
    DOCUMENTO_VALORADO_EN_CURSO: 2,
    FECHA_VIGENCIA_TEMPORAL: 3,

    //Solicitud Condición de Pago
    ESTADO_CONDICION_PAGO_SOLICITANTE: 10,
    ESTADO_CONDICION_PAGO_EVALUADOR: 40,
    ESTADO_CONDICION_PAGO_APROBADOR: 220,
    ESTADO_CONDICION_PAGO_APROBADOR_SOLICITANTE: 211,
    ESTADO_CONDICION_PAGO_ACTIVADOR: 230,

    //Solicitud grupo/Consorcio
    ESTADO_SOLICITUD_GRUPO_CONSORCIO_BORRADOR: 10,
    ESTADO_SOLICITUD_GRUPO_CONSORCIO_APROBADO: 20,
    ESTADO_SOLICITUD_GRUPO_CONSORCIO_PENDIENTE_ACTIVAR_NUEVO: 40,
    ESTADO_SOLICITUD_GRUPO_CONSORCIO_PENDIENTE_ACTIVAR_EXISTENTE: 41,
    ESTADO_SOLICITUD_GRUPO_CONSORCIO_PENDIENTE_DESACTIVAR: 50,

    //TIPO CLIENTE
    TIPO_CLIENTE_GRUPO_EMPRESARIAL:1,
    TIPO_CLIENTE_CONSORCIO:2,
    TIPO_CLIENTE_EMPRESA_INDIVIDUAL:3,

})